# -*- coding: utf-8 -*-
"""Finance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14o7teEmFlwvZbLlgNlfm673J7D97VKtT

# **Analysis of Finance dataset**
### Author: Vejaykarthy Srithar
"""

# Installs

!pip install python-dotenv

# Imports

import os
import requests
import dotenv
import pandas as pd
import matplotlib.pyplot as plt

from datetime import datetime
from google.colab import drive

# Mount

dotenv.load_dotenv('/content/.env')

# Constants

APIKEY = os.environ.get('APIKEY')

NAME_FUNCTION = 'function='
NAME_APIKEY = '&apikey='
NAME_FROM_SYMBOL = '&from_symbol='
NAME_TO_SYMBOL = '&to_symbol='

VALUE_FUNCTION = 'FX_DAILY'
VALUE_FROM_SYMBOL = 'AUD'
VALUE_TO_SYMBOL = 'USD'

URL_BASE = 'https://www.alphavantage.co/query?'
URL_FX_DAILY = URL_BASE + NAME_FUNCTION + VALUE_FUNCTION + NAME_FROM_SYMBOL + VALUE_FROM_SYMBOL + NAME_TO_SYMBOL + VALUE_TO_SYMBOL + NAME_APIKEY + APIKEY

r = requests.get(URL_FX_DAILY)
data = r.json()

data_list = []
for date in data['Time Series FX (Daily)']:
  data['Time Series FX (Daily)'][date]['date'] = datetime.strptime(date, '%Y-%m-%d').date()
  data_list.append(data['Time Series FX (Daily)'][date])
df = pd.DataFrame(data_list)
df.columns = ['Open', 'High', 'Low', 'Close', 'Date']
df['Open'] = df['Open'].apply(lambda x: float(x))
df['High'] = df['High'].apply(lambda x: float(x))
df['Low'] = df['Low'].apply(lambda x: float(x))
df['Close'] = df['Close'].apply(lambda x: float(x))

plt.plot(df['Date'],df['Open'],color='blue')
plt.plot(df['Date'],df['Close'],color='red')
plt.plot(df['Date'],df['High'],color='green')
plt.plot(df['Date'],df['Low'],color='orange')